### ISSUE TITLE
defect subtitles all over the place on ios11

### ISSUE THREAD

**Issue by 42sol-eu** [V-Play/QtWorldSummit2017#1] opened 2017-09-29 19:56 UTC
there are extremely many text scrambled for example all sublines of the presenters.
Picture following.
Device ios11 on  iPhone
Felix

**Comment by feldifux** [comment] 2017-10-01 20:43
Hi Felix,
can you share a screenshot where you see the text scrambled please?

**Comment by 42sol-eu** [comment] 2017-10-02 11:34
shure - same on the ipad. sometimes after reloading 

ios11
language english
location germany


// Felix Haeberle
@deloriel42

**Comment by feldifux** [comment] 2017-10-03 01:19
We could not identify any "scrambled text" issues on our iOS 11 test devices. Please share a screenshot so we can have a look.

The auto-country language issue is already fixed and will be submitted with the next app update today.

**Comment by sk2212** [comment] 2017-10-06 08:14
@feldifux Can you please tell me how you fix the language issue for iOS 11? We found no other way than doing it directly in a platform depended way.

There was no solution to fix this with Qt itself.

**Comment by feldifux** [comment] 2017-10-06 10:11
@sk2212 sure! we are using Qt.locale().name to get the system locale, works on all platforms

**Comment by sk2212** [comment] 2017-10-06 11:32
Ok, this is the QML way, but in Qt we have following code to translate our application:

    QString locale = QLocale::system().name();
    if (!locale.startsWith("de"))
    {
      qtTranslator.load(":/i18n/en_GB");
      app.installTranslator(&qtTranslator);
    }

The problem is now that with iOS11 "QLocale::system().name()" returns "en_" although you have choosed "de" as default language. 

You just have to add "English" as another language and still have set "German" as default but QLocale::system().name() will return "en_".

**Comment by 42sol-eu** [comment] 2017-10-09 07:18
Hi,
IPhone is fine. IPad one effect on first start. After reload no issues found.
Sincerly 
  Felix

// Felix Haeberle
@deloriel42

**Comment by Talkless** [comment] 2017-10-09 10:18
Maybe it's the same issue mentioned here:
https://bugreports.qt.io/browse/QTBUG-63127

**Comment by Talkless** [comment] 2017-10-10 13:47
@42sol-eu could you check bug report I've mentioned?

**Comment by GTeufl** [comment] 2021-07-14 09:48
The general issues with text rendering on iOS are already solved, closing the issue

**Closed as completed by GTeufl** 2021-07-14 09:48 UTC
